### ISSUE TITLE
Update Community libraries in Sendgrid Page

### ISSUE THREAD

**Issue by MIKNOTAURO** [sklarsa/django-sendgrid-v5#18]
I saw this library on the official website a few months ago, and now it disappeared.
I would like to know why, Is there any reason?
I think it's the best place to be and get feedback.
Btw, the name should be like django-sendgrid-backend or something like that
just to not be tied to a special sendgrid-python version.

Anyway, thanks for your contribution.

**Comment by sklarsa** [comment]
It's still there: https://sendgrid.com/docs/Integrate/Frameworks/django.html

I named it V5 because there were older, unmaintained libraries with names
that made sense.  I'm ok with `django-sendgrid-backend`, I just need a
little time to change the repo name and pypi configs, and find a clear way
to redirect users to the new name.

**Comment by MIKNOTAURO** [comment]
I said it because here
https://sendgrid.com/docs/Integrate/libraries.html
is the other libraries.
I don't know if this is under your control, but I think that should be here too.

**Comment by sklarsa** [comment]
Ah good catch!  Those docs are open sourced on github, so you can make a PR here: https://github.com/sendgrid/docs/blob/develop/source/Integrate/libraries.md

I won't be able to get to it until later, but please feel free to make a PR there and update the docs.  Let me know once you've done it on this thread so we don't duplicate effort :-)

Thanks!!

**Comment by sklarsa** [comment]
https://github.com/sendgrid/docs/pull/3526
